// angular/angular-backend/src/app/shared/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../../pages/login/auth.service';

@Component({
  selector: 'app-sidebar',
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './sidebar.component.html',
  styleUrl: './sidebar.component.css'
})
export class SidebarComponent {

  constructor(private authService: AuthService) {}

  logout() {
    this.authService.logout(); // Call logout function
  }

}

<ul class="list-group mt-3 pt-2 custom-sidebar">
    <li class="list-group-item" aria-current="true">
      <a routerLink="/admin/dashboard" routerLinkActive='active'>Dashboard</a>
    </li>
    <li class="list-group-item" aria-current="true">
      <a routerLink="/admin/about/list" routerLinkActive='active'>Manage About</a>
    </li>
    <li class="list-group-item" aria-current="true">
      <a routerLink="/admin/contact/list" routerLinkActive='active'>Manage Contact</a>
    </li>
    <li class="list-group-item" aria-current="true">
      <a routerLink="/admin/faq/list" routerLinkActive='active'>Manage FAQ</a>
    </li>
    <!-- <li class="list-group-item" aria-current="true">
      <a routerLink="/admin/portfolio" routerLinkActive='active'>Manage Portfolio</a>
    </li> -->
    <li class="list-group-item" aria-current="true">
      <a routerLink="/admin/service/list" routerLinkActive='active'>Manage Service</a>
    </li>          
    <li class="list-group-item" aria-current="true">
      <a routerLink="/admin/brand/list" routerLinkActive='active'>Manage Brand</a>
    </li>
    <li class="list-group-item" aria-current="true">
      <a routerLink="/admin/category/list" routerLinkActive='active'>Manage Category</a>
    </li>
    <li class="list-group-item" aria-current="true">
      <a routerLink="/admin/product/list" routerLinkActive='active'>Manage Product</a>
    </li>
    <!-- <li class="list-group-item" aria-current="true">
      <a routerLink="/admin/order" routerLinkActive='active'>Manage Order</a>
    </li>
    <li class="list-group-item" aria-current="true">
      <a routerLink="/admin/product-enquiry" routerLinkActive='active'>Manage Product Enquiry</a>
    </li> -->
    <li class="list-group-item" aria-current="true">
      <a routerLink="/admin/user/list" routerLinkActive='active'>Manage User</a>
    </li>
    <li class="list-group-item" aria-current="true">
      <a (click)="logout()">Logout</a>
    </li>
  </ul>

// react/react-backend/src/components/common/Sidebar.jsx
import React from 'react';
import { NavLink } from 'react-router-dom';


const Sidebar = () => {
  return (
    <>
        <ul className="list-group mt-3 custom-sidebar">
          <li className="list-group-item" aria-current="true">
            <NavLink to="/dashboard" activeClassName='active'>Dashboard</NavLink>
          </li>
          <li className="list-group-item" aria-current="true">
            <NavLink to="/about/list" activeClassName='active'>Manage About</NavLink>
          </li>
          <li className="list-group-item" aria-current="true">
            <NavLink to="/contact/list" activeClassName='active'>Manage Contact</NavLink>
          </li>
          <li className="list-group-item" aria-current="true">
            <NavLink to="/faq/list" activeClassName='active'>Manage FAQ</NavLink>
          </li>
          <li className="list-group-item" aria-current="true">
            <NavLink to="/portfolio/list" activeClassName='active'>Manage Portfolio</NavLink>
          </li>
          <li className="list-group-item" aria-current="true">
            <NavLink to="/service/list" activeClassName='active'>Manage Service</NavLink>
          </li>          
          <li className="list-group-item" aria-current="true">
            <NavLink to="/brand/list" activeClassName='active'>Manage Brand</NavLink>
          </li>
          <li className="list-group-item" aria-current="true">
            <NavLink to="/category/list" activeClassName='active'>Manage Category</NavLink>
          </li>
          <li className="list-group-item" aria-current="true">
            <NavLink to="/product/list" activeClassName='active'>Manage Product</NavLink>
          </li>
          <li className="list-group-item" aria-current="true">
            <NavLink to="/order/list" activeClassName='active'>Manage Order</NavLink>
          </li>
          <li className="list-group-item" aria-current="true">
            <NavLink to="/product-enquiry/list" activeClassName='active'>Manage Product Enquiry</NavLink>
          </li>
          <li className="list-group-item" aria-current="true">
            <NavLink to="/user/list" activeClassName='active'>Manage User</NavLink>
          </li>
        </ul>
    </>
  )
}

export default Sidebar
