// angular/angular-backend/src/app/layouts/common-layout/common-layout.component.ts
import { Component } from '@angular/core';
import { HeaderComponent } from '../../shared/components/header/header.component';
import { FooterComponent } from '../../shared/components/footer/footer.component';
import { SidebarComponent } from '../../shared/components/sidebar/sidebar.component';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-common-layout',
  imports: [HeaderComponent, FooterComponent, SidebarComponent, RouterOutlet],
  templateUrl: './common-layout.component.html',
  styleUrl: './common-layout.component.css'
})
export class CommonLayoutComponent {

}

<app-header></app-header>
<div class='container-fluid'>
<div class='row'>
    <div class='col-lg-2'>
        <app-sidebar></app-sidebar>
    </div>
    <div class='col-lg-10'>
    <div class='mt-3 border border-2 border-black p-3'>
        <router-outlet></router-outlet>
    </div>            
    </div>
</div>
</div>
<app-footer></app-footer>

// react/react-backend/src/layouts/CommonLayout.js
import React from 'react';
import Header from '../components/common/Header';
import Footer from '../components/common/Footer';
import Sidebar from '../components/common/Sidebar';
import "../assets/css/common-layout.css";

const CommonLayout = ({ children }) => {
  return (
    <>
      <Header />
      <div className='container-fluid'>
        <div className='row'>
          <div className='col-lg-2'>
              <Sidebar />
          </div>
          <div className='col-lg-10'>
            <div className='mt-3 border border-2 border-black p-3'>
              {children}
            </div>            
          </div>
        </div>
      </div>
      <Footer />
    </>
  )
}

export default CommonLayout
